export const BOOKS_REQUESTED = 'BOOKS/REQUESTED';
export const BOOKS_RECEIVED = 'BOOKS/RECEIVED';
export const BOOKS_RECEIVED_MORE = 'BOOKS/RECEIVED_MORE';
export const BOOKS_ERROR = 'BOOKS/ERROR';

export const BOOK_REQUESTED = 'BOOK/REQUESTED';
export const BOOK_RECEIVED = 'BOOK/RECEIVED';
export const BOOK_ERROR = 'BOOK/ERROR';

export const SET_PAGE = 'PAGES/SET';
export const NEXT_PAGE = 'PAGES/NEXT_PAGE';

export const SEARCH_SET_CATEGORY = 'SEARCH/SET_CATEGORY';
export const SEARCH_SET_SORTING = 'SEARCH/SET_SORTING';
